<?php
/**
 * @file
 * Adds another form element to filter multiple exposed filter.
 */

/**
 * Implements hook_views_api().
 */
function filterable_views_filter_views_api() {
  return array(
    'api' => 3.0,
  );
}

/**
 * Add states extension for multiselect problems until #1149078 is fixed.
 */
function filterable_views_filter_page_build(&$page) {
  ctools_add_js('filterable_views_filter', 'filterable_views_filter');
}

/**
 * Implements hook_init().
 *
 * Unset the filterable_views_filter value for views.
 */
function filterable_views_filter_init() {
  if (isset($_GET['filterable_views_filter'])) {
    unset($_GET['filterable_views_filter']);
  }
}
